configfile: "config/config.yml"


rule all:
    input:
        "results/plots/moment0_map.png",
        "results/plots/moment1_map.png",
        "results/plots/moment2_map.png"


rule download_data:
    output:
        "data/cube/NGC_3198_NA_CUBE_THINGS.fits",
    shell:
        """
        wget -P data/cube {config[datacube_path]}
        """


rule run_sofia:
    input:
        "data/cube/NGC_3198_NA_CUBE_THINGS.fits",
    output:
        "data/sofia-output/NGC_3198_mom0.fits",
        "data/sofia-output/NGC_3198_mom1.fits",
        "data/sofia-output/NGC_3198_mom2.fits"
    shell:
        "sofia data/sofia.par"


rule plot_moment0:
    input:
        "data/sofia-output/NGC_3198_mom0.fits",
    output:
        "results/plots/moment0_map.png",
    conda:
        "envs/plotfits.yml"
    script:
        "scripts/plot_moment0.py"


rule plot_moment1:
    input:
        "data/sofia-output/NGC_3198_mom1.fits",
    output:
        "results/plots/moment1_map.png"
    conda:
        "envs/plotfits.yml"
    script:
        "scripts/plot_moment1.py"


rule plot_moment2:
    input:
        "data/sofia-output/NGC_3198_mom2.fits",
    output:
        "results/plots/moment2_map.png"
    conda:
        "envs/plotfits.yml"
    script:
        "scripts/plot_moment2.py"

